%YAML:1.0
ukd_base_bias: 0.0    # 方位角偏差。单位度。
ukd_tag_bias: 25.0      # 标签AOA角度偏差。单位度。
ukd_tag_coeff: 1.0      # 标签AOA角度斜率。
ukd_distance_bias: 0.0  # 距离偏差。单位m。
# rotation_compensation_clockwise: -0.05  # 角速度补偿系数（顺时针）
# rotation_compensation_counter: -0.05    # 角速度补偿系数（逆时针）
rotation_compensation_clockwise: -0.00  # 角速度补偿系数（顺时针）
rotation_compensation_counter: -0.00    # 角速度补偿系数（逆时针）