%YAML:1.0
distance_start: 0.5
distance_end: 2.5
duration: 600
rotate_speed: 0.3
tag_height: 1.0
base_height: 0.4
vx_bias: 0.0  # x方向速度指令的校准值
vy_bias: 0.0  # y方向速度指令的校准值
rotate_radius: 0.26  # 基站坐标系相对"base_link"的偏移量

# 图片跟踪的目标像素位置
picture_goal_x: 320
picture_goal_y: 240
picture_px: 0.0007 # P控制系数
picture_py: 0.0007