(cl:in-package a2_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          LX-VAL
          LX
          LY-VAL
          LY
          RX-VAL
          RX
          RY-VAL
          RY
          UP-VAL
          UP
          RIGHT-VAL
          RIGHT
          DOWN-VAL
          DOWN
          LEFT-VAL
          LEFT
          A-VAL
          A
          B-VAL
          B
          X-VAL
          X
          Y-VAL
          Y
          L1-VAL
          L1
          L2-VAL
          L2
          R1-VAL
          R1
          R2-VAL
          R2
          F1-VAL
          F1
          SELECT-VAL
          SELECT
          F2-VAL
          F2
          START-VAL
          START
))