(cl:in-package a2_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          TX-VAL
          TX
          TY-VAL
          TY
          TZ-VAL
          TZ
          TA-VAL
          TA
          TO-VAL
          TO
          TP-VAL
          TP
          TD-VAL
          TD
          T_ROLL-VAL
          T_ROLL
          T_PITCH-VAL
          T_PITCH
          T_YAW-VAL
          T_YAW
          T_VALID-VAL
          T_VALID
          EST_SUC_COUNT-VAL
          EST_SUC_COUNT
          ROCKER0_X-VAL
          ROCKER0_X
          ROCKER0_Y-VAL
          ROCKER0_Y
          BUTTON0-VAL
          BUTTON0
          BUTTON1-VAL
          BUTTON1
          BUTTON2-VAL
          BUTTON2
          BUTTON3-VAL
          BUTTON3
          BUTTONS_MODE-VAL
          BUTTONS_MODE
          JOY_MODE-VAL
          JOY_MODE
))