// Generated by gencpp from file a2_msgs/Joystick.msg
// DO NOT EDIT!


#ifndef A2_MSGS_MESSAGE_JOYSTICK_H
#define A2_MSGS_MESSAGE_JOYSTICK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace a2_msgs
{
template <class ContainerAllocator>
struct Joystick_
{
  typedef Joystick_<ContainerAllocator> Type;

  Joystick_()
    : header()
    , rockers()
    , buttons()  {
    }
  Joystick_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , rockers(_alloc)
    , buttons(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _rockers_type;
  _rockers_type rockers;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _buttons_type;
  _buttons_type buttons;





  typedef boost::shared_ptr< ::a2_msgs::Joystick_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::a2_msgs::Joystick_<ContainerAllocator> const> ConstPtr;

}; // struct Joystick_

typedef ::a2_msgs::Joystick_<std::allocator<void> > Joystick;

typedef boost::shared_ptr< ::a2_msgs::Joystick > JoystickPtr;
typedef boost::shared_ptr< ::a2_msgs::Joystick const> JoystickConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::a2_msgs::Joystick_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::a2_msgs::Joystick_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::a2_msgs::Joystick_<ContainerAllocator1> & lhs, const ::a2_msgs::Joystick_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.rockers == rhs.rockers &&
    lhs.buttons == rhs.buttons;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::a2_msgs::Joystick_<ContainerAllocator1> & lhs, const ::a2_msgs::Joystick_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace a2_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::a2_msgs::Joystick_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::a2_msgs::Joystick_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::a2_msgs::Joystick_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::a2_msgs::Joystick_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::a2_msgs::Joystick_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::a2_msgs::Joystick_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::a2_msgs::Joystick_<ContainerAllocator> >
{
  static const char* value()
  {
    return "52ec0782af3d653b2a5ae5f4e05ef6e6";
  }

  static const char* value(const ::a2_msgs::Joystick_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x52ec0782af3d653bULL;
  static const uint64_t static_value2 = 0x2a5ae5f4e05ef6e6ULL;
};

template<class ContainerAllocator>
struct DataType< ::a2_msgs::Joystick_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a2_msgs/Joystick";
  }

  static const char* value(const ::a2_msgs::Joystick_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::a2_msgs::Joystick_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"# 摇杆\n"
"float32[] rockers  # 摇杆从左到右，从下到上，对应值域[-1.0, 1.0]\n"
"\n"
"# 按键\n"
"uint8[] buttons\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::a2_msgs::Joystick_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::a2_msgs::Joystick_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.rockers);
      stream.next(m.buttons);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Joystick_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::a2_msgs::Joystick_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::a2_msgs::Joystick_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "rockers[]" << std::endl;
    for (size_t i = 0; i < v.rockers.size(); ++i)
    {
      s << indent << "  rockers[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.rockers[i]);
    }
    s << indent << "buttons[]" << std::endl;
    for (size_t i = 0; i < v.buttons.size(); ++i)
    {
      s << indent << "  buttons[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.buttons[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // A2_MSGS_MESSAGE_JOYSTICK_H
